# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(545, 436)
        self.layout_dialog = QtWidgets.QVBoxLayout(Dialog)
        self.layout_dialog.setObjectName("layout_dialog")
        self.widget_plot_1 = QtWidgets.QWidget(Dialog)
        self.widget_plot_1.setObjectName("widget_plot_1")
        self.layout_plot_1 = QtWidgets.QVBoxLayout(self.widget_plot_1)
        self.layout_plot_1.setObjectName("layout_plot_1")
        self.layout_dialog.addWidget(self.widget_plot_1)
        self.widget_plot_2 = QtWidgets.QWidget(Dialog)
        self.widget_plot_2.setObjectName("widget_plot_2")
        self.layout_plot_2 = QtWidgets.QVBoxLayout(self.widget_plot_2)
        self.layout_plot_2.setObjectName("layout_plot_2")
        self.layout_dialog.addWidget(self.widget_plot_2)
        self.btn_without_gas = QtWidgets.QPushButton(Dialog)
        self.btn_without_gas.setObjectName("btn_without_gas")
        self.layout_dialog.addWidget(self.btn_without_gas)
        self.btn_with_gas = QtWidgets.QPushButton(Dialog)
        self.btn_with_gas.setObjectName("btn_with_gas")
        self.layout_dialog.addWidget(self.btn_with_gas)
        self.btn_difference = QtWidgets.QPushButton(Dialog)
        self.btn_difference.setObjectName("btn_difference")
        self.layout_dialog.addWidget(self.btn_difference)
        self.widget_threshold = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_threshold.sizePolicy().hasHeightForWidth())
        self.widget_threshold.setSizePolicy(sizePolicy)
        self.widget_threshold.setObjectName("widget_threshold")
        self.layout_threshold = QtWidgets.QHBoxLayout(self.widget_threshold)
        self.layout_threshold.setContentsMargins(0, 0, 0, 0)
        self.layout_threshold.setObjectName("layout_threshold")
        self.label_threshold = QtWidgets.QLabel(self.widget_threshold)
        self.label_threshold.setObjectName("label_threshold")
        self.layout_threshold.addWidget(self.label_threshold)
        self.lineEdit_threshold = QtWidgets.QLineEdit(self.widget_threshold)
        self.lineEdit_threshold.setObjectName("lineEdit_threshold")
        self.layout_threshold.addWidget(self.lineEdit_threshold)
        self.pushButton_threshold = QtWidgets.QPushButton(self.widget_threshold)
        self.pushButton_threshold.setObjectName("pushButton_threshold")
        self.layout_threshold.addWidget(self.pushButton_threshold)
        self.layout_dialog.addWidget(self.widget_threshold)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_without_gas.setText(_translate("Dialog", "Загрузка из файла без вещества"))
        self.btn_with_gas.setText(_translate("Dialog", "Загрузка файла с вещством "))
        self.btn_difference.setText(_translate("Dialog", "Разность"))
        self.label_threshold.setText(_translate("Dialog", "Порог [%]"))
        self.lineEdit_threshold.setText(_translate("Dialog", "40"))
        self.pushButton_threshold.setText(_translate("Dialog", "Расчёт порогового значения"))
